site_name: enchantr
site_url: https://enchantr.readthedocs.io
site_favicon: img/favicon.ico
repo_url: https://github.com/immcantation/enchantr
edit_uri: src/master/docs/
theme: readthedocs
site_name: enchantr
docs_dir: docs
markdown_extensions:
  - admonition
  - def_list
  - sane_lists
  - smarty
  - toc:
      permalink: True
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - path: js/custom.js
    defer: true
extra_css:
  - css/custom.css
nav:
  - 'Immcantation Portal': https://immcantation.readthedocs.io/
  - 'About':
    - 'Introduction': index.md
    - 'Download & Installation': install.md
    - 'Package Overview': topics/enchantr.md
    - 'Release Notes': news.md
    - 'Related Projects': projects.md
  - 'Vignettes':
    - 'enchantR reports': vignettes/enchantr-vignette.md
  - 'Help Topics':
    - 'Reports':
      - topics/chimera_analysis_project.md
      - topics/collapse_duplicates_project.md
      - topics/contamination_project.md
      - topics/single_cell_qc_project.md
      - topics/find_threshold_project.md
      - topics/define_clones_project.md
      - topics/dowser_lineage_project.md

